version: "3"
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
        - DATABASE_ENGINE=django.db.backends.postgresql
        - DATABASE_DB=django_db
        - DATABASE_USER=django_db_user
        - DATABASE_PASSWORD=password1234
        - DATABASE_HOST=db
        - DATABASE_PORT=5432
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=django_db_user
      - POSTGRES_PASSWORD=password1234
      - POSTGRES_DB=django_db